language: php

php:
  - 5.6
  - 7.2

cache:
  - composer

before_script:
  - make
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs
  on:
    php: 7.2
    branch: master
